<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DBL0MJR" failures="0" tests="5" name="testclass.loginTest" time="16.272" errors="1" timestamp="2019-12-03T15:51:11 IST" skipped="1">
  <testcase classname="testclass.loginTest" name="Blank_Submit_Login" time="1.252"/>
  <testcase classname="testclass.loginTest" name="Login_with_wrong_Email" time="0.492"/>
  <testcase classname="testclass.loginTest" name="Login_with_wrong_Password" time="4.585"/>
  <testcase classname="testclass.loginTest" name="Login_With_Valid_Credentials" time="9.943">
    <error message="class java.util.ArrayList cannot be cast to class com.sun.tools.javac.util.List (java.util.ArrayList is in module java.base of loader &#039;bootstrap&#039;; com.sun.tools.javac.util.List is in module jdk.compiler of loader &#039;app&#039;)" type="java.lang.ClassCastException">
      <![CDATA[java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class com.sun.tools.javac.util.List (java.util.ArrayList is in module java.base of loader 'bootstrap'; com.sun.tools.javac.util.List is in module jdk.compiler of loader 'app')
at testCases.Login.Login_with_Valid_Credentials(Login.java:130)
at testclass.loginTest.Login_With_Valid_Credentials(loginTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Login_With_Valid_Credentials -->
  <testcase classname="testclass.loginTest" name="GoToProfile">
    <skipped/>
  </testcase> <!-- GoToProfile -->
</testsuite> <!-- testclass.loginTest -->
